{% set version = "1.5.4" %}

package:
  name: shellingham
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/shellingham/shellingham-{{ version }}.tar.gz
  sha256: 8dbca0739d487e5bd35ab3ca4b36e11c4078f3a234bfce294b0a0291363404de

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - shellingham
    - shellingham.posix
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/sarugaku/shellingham
  license: ISC
  license_family: OTHER
  license_url: https://github.com/sarugaku/shellingham/blob/master/LICENSE
  summary: Tool to Detect Surrounding Shell
  description: Shellingham detects what shell the current Python executable is running in.
  dev_url: https://github.com/sarugaku/shellingham/tree/master
  doc_url: https://github.com/sarugaku/shellingham#readme

extra:
  recipe-maintainers:
    - ocefpaf
